### ISSUE TITLE
eem_raman_normalisation for EEMs from aqualog

### ISSUE THREAD

**Issue by markjohnsonubc** [PMassicotte/eemR#31]
The eem_raman_normalisation wants to normalize based on excitation of 350nm, but Aqualog outputs data for ex = 351 nm. 

A suggestion would be to add the condition that if manucafturer: Aqualog == TRUE then use ex == 351
  index_ex <- which(blank$ex == 351)

Also note spelling of manucafturer

We are able to get Raman area output when setting a local function to use ex==351.

Thanks
Mark

**Comment by PMassicotte** [comment]
Hi @markjohnsonubc 

I am not sure to understand what you say. Are you saying that Aqualog recommends to use 351?

**Comment by markjohnsonubc** [comment]
hi @PMassicotte 

Here are the excitation wavelengths that are in the eem files output from aqualog:
$ex
  [1] 240 243 246 249 252 255 258 261 264 267 270 273 276 279 282 285 288 291 294 297 300 303 306 309 312 315 318 321 324 327 330 333 336 339 342 345 348 **351** 354 357 360 363 366 369 372 375 378 381 384 387 390 393 396 399 402 405 408 411 414 417 420 423 426 429 432 435 438 441 444 447 450 453 456 459 462 465 468 471 474 477 480 483 486 489 492 495 498 501 504 507 510 513 516 519 522 525 528 531 534 537 540 543 546 549 552 555 558 561 564 567 570 573 576 579 582 585 588 591 594 597 600

I've bolded the 351 nm. Options seem to be interpolating the EEM to produce an emission vector for ex == 350 nm, or simply taking the emission vector corresponding to ex == 351nm. 

Without this change, the function outputs Raman area = 0.

**Comment by PMassicotte** [comment]
Ok I understand. Most functions interpolate when the precise wl is not found. I will do it tomorrow and post an update.

**Comment by markjohnsonubc** [comment]
That's terrific. Really liking the package - thanks for your efforts on it!

**Comment by PMassicotte** [comment]
@markjohnsonubc can you try the `raman-fix` branch to see if it is working?

**Comment by markjohnsonubc** [comment]
Working indeed. Thanks!
