### ISSUE TITLE
Absorbance spectrum not found (eem_inner_filter_effect)

### ISSUE THREAD

**Issue by markjohnsonubc** [PMassicotte/eemR#33]
Working with output from Aqualog, I've ensured that sample names in absorbance files match those in the EEMs. I wrote a bit of code to extrapolate and interpolate the absorbance file to provide absorbance data for all Ex and Em wavelengths.  However, the function eem_inner_filter_effect doesn't identify the absorbance spectrum within the absorbance data.frame. 

I've tried with both single EEM and as eemlist, as well as ensuring no spaces or other non-alphanumeric characters in sample names. 

Stepping through the function, I could get it to match the spectra using the line below
  spectra <- absorbance[, which(names(absorbance) == unlist(lapply(eem, "[[", 1)))]

  ex <- sf(unlist(lapply(eem, "[[", 3)))
  em <- sf(unlist(lapply(eem, "[[", 4)))

![image](https://cloud.githubusercontent.com/assets/10761097/16609685/d74d2148-430a-11e6-9a55-8e446bc68be3.png)

Any thoughts? 

Thanks

**Comment by PMassicotte** [comment]
Interesting. Can you try the dev version of the package?

**Comment by markjohnsonubc** [comment]
This is running the dev version via
devtools::install_github("PMassicotte/eemR")

The examples do work. Would it help to send you any files?

**Comment by PMassicotte** [comment]
Yes please. Because I have no idea at the moment since I can't replicate the problem.

**Comment by markjohnsonubc** [comment]
Here are 5 EEMs, a blank file, and an absorbance file (abs.csv) containing the absorbance spectra for the 5 files
[4eemR.zip](https://github.com/PMassicotte/eemR/files/352589/4eemR.zip)

**Comment by PMassicotte** [comment]
I just fixed the issue. At some place I was using `tolower` on the absorbance names which caused as mismatch. I tested with your data and it is working fine now.

**Comment by markjohnsonubc** [comment]
Confirmed also working for me. Thanks!
