### ISSUE TITLE
eem_extract() doesn't extract multiple files

### ISSUE THREAD

**Issue by markjohnsonubc** [PMassicotte/eemR#37]
The example suggests it should, but resulting eemlist only extracts first eem in vector. 

folder <- system.file("extdata/cary/scans_day_1", package = "eemR")
eems.test <- eem_read(folder)
eems.test
eems.test2 <- eem_extract(eems.test, c(1, 3, 4)) ## Remove samples 1, 3 and 4
eems.test2  #only removed 1st eem from vector c(1,3,4)

**Comment by PMassicotte** [comment]
Does it works if you try:

`eem_extract(eems.test, c(1, 3, 4), remove = T) `

**Comment by PMassicotte** [comment]
Been working to make the function more intuitive.

You can try the dev version.

```r
eem_extract(eems.test, c(1, 3, 4), keep = TRUE) 
```

**Comment by markjohnsonubc** [comment]
Great - this works well for both keep = TRUE and keep = FALSE
