### ISSUE TITLE
interactive plot error

### ISSUE THREAD

**Issue by julienleroux5** [PMassicotte/eemR#38]
Hi Philippe,

I am testing your package, it's really great work, very useful.
I was getting an error with the interactive mode when trying to plot data from your examples (cary data):
`Error: attempt to select less than one element in get1index`

Julien

**Comment by PMassicotte** [comment]
Hi @julienleroux5!

Can you try to click 1 line in the table? I think it is a bug when you first open the interactive plot because no EEMs is selected.

**Comment by julienleroux5** [comment]
Thanks Philippe, it worked. Will try your package with some of my data more in-depth soon. I am really looking forward to seeing your parafac adaptation to R!
