### ISSUE TITLE
Fluoromax 4 files

### ISSUE THREAD

**Issue by gjgetzinger** [PMassicotte/eemR#40]
Here are ASCII exports from a Fluoromax 4: 
[https://polybox.ethz.ch/index.php/s/4yJmhLooALSHP1O](url)

Let me know if you need anything else to add compatibility for that file type to eemR. 

Thanks! 

Gordon

**Comment by PMassicotte** [comment]
I will work on that this week. These are raw files produced by the software?

**Comment by gjgetzinger** [comment]
No, those files were created by batch export of the raw data. would you prefer them in instrument-generated file format?

**Comment by PMassicotte** [comment]
I am not sure to understand the *batch export thing*. What the package use is the human-readable data exported by the software.

**Comment by gjgetzinger** [comment]
The instrument uses orgin workbooks to store raw data. the user can select a single file or multiple files to export in ASCII format. The available extensions are .dat, .csv and .txt. 

Feel free to use the files. MQblk is, as you probably guessed, a milli-q blank. Pool01 and SH7 are DOM samples.

**Comment by gjgetzinger** [comment]
*Origin

**Comment by PMassicotte** [comment]
I updated the package. It should be able to read fluoromax 4 data. You can try installing the dev version.
