### ISSUE TITLE
Export to Matlab Error

### ISSUE THREAD

**Issue by DannyC91** [PMassicotte/eemR#41]
Hi, Using the export to Matlab function with version 0.1.4, when it gets exported the x field exports as a single column of data rather than as a matrix. I don't think it's anything i've done as the same error occurred going through with the source code data too.

**Comment by PMassicotte** [comment]
You just need to reshape the X matrix. It is a bug from the package that I use to export the matrix.

 ```matlab
load('../data/clean/OriginalData.mat');

OriginalData.X = reshape(OriginalData.X, OriginalData.nSample, OriginalData.nEm, OriginalData.nEx);
```

**Comment by DannyC91** [comment]
Thanks, also do you know how to access the  eem_read_parafac function, or is that still in development?

**Comment by PMassicotte** [comment]
You have the install the dev branch:

```r
devtools::install_github("pmassicotte/eemR", ref = "plot-parafac")
```
