### ISSUE TITLE
Error message when trying to load eemR

### ISSUE THREAD

**Issue by Patty726coops** [PMassicotte/eemR#43]
eemR can be installed successfully in R but when trying to load eemR the attached error message appears.
![capture of error code for eemr package](https://cloud.githubusercontent.com/assets/26922140/24699344/955f1f44-19eb-11e7-8094-da6d159e7cb8.PNG)
This has only happened when trying to use the package since the beginning of April 2016 I did not use the package in March 2016 but prior to that it worked well. 
I have uninstalled/ re-installed R  with the same error appearing every time

**Comment by PMassicotte** [comment]
I think the error message is pretty clear.

> there is no package called `viridisLite`

Install missing packages and it should work.
