### ISSUE TITLE
import data 

### ISSUE THREAD

**Issue by zier1333** [PMassicotte/eemR#44]
I am so sorry for bothering you. I have some questions to ask you, how to import data. I have tried many times, it always shows as follows. 
Thank you for your reading, I am looking forwards to your reply.

![image](https://cloud.githubusercontent.com/assets/27997237/25375661/5fadf798-29dc-11e7-9237-1b0477f8f6ee.png)

**Comment by PMassicotte** [comment]
```r
eem_read("c"/dv/eem")
```

**Comment by zier1333** [comment]
Using csv format, but it can not read.
![image](https://cloud.githubusercontent.com/assets/27997237/25417440/19a6bff2-2a7f-11e7-8b1e-b5988aab9e5a.png)

**Comment by zier1333** [comment]
then importing "summary(eem)",  it shows "NULL" I guess the reason is the format. The format of my data is from Hitachi. Is it correct? What should I do? 
[eem.zip](https://github.com/PMassicotte/eemR/files/957239/eem.zip)

**Comment by PMassicotte** [comment]
It is because the package is not able to currently read Hitachi files (I never played with those before). I can try to work on that soon.

**Comment by zier1333** [comment]
Anyway, thank you for your help. The zip includes some Hitachi files as above, I hope it can provide some reference for you.

**Comment by PMassicotte** [comment]
@zier1333 do you still need it?

**Comment by maetz13** [comment]
@PMassicotte I was working on import of Hitachi files last weekend and added some functions to your code (just for me at the moment). Did you already do something on the topic, are you maybe interested in my work?

**Comment by PMassicotte** [comment]
@maetz13 which kind of function? They might be interesting.

**Comment by maetz13** [comment]
@PMassicotte its is_hitachi() and eem_read_hitachi() as close as possible to your script. The functions work well for me at the moment. There may be 2 shortcomings:

- as I do not know any other formats is_hitachi() looks for F-7000 which is the model I use. maybe there is a more general and more robust way.

- eem_read_hitachi() is still a bit dirty but working.

[eem_read_hit.zip](https://github.com/PMassicotte/eemR/files/979217/eem_read_hit.zip)

**Comment by zier1333** [comment]
yes, I really need it.  My format is also HITACHI F7000, actually, I perfect to use R rather than use Matlab to process the data, it contains removing Raman scattering and using some indices. As for beginner, It is so difficult for me to operate Matlab.

**Comment by PMassicotte** [comment]
@zier1333 Are you sure that file I1(FD3).TXT is untouched file from the spectrofluo? It contains "hole" in it.

**Comment by PMassicotte** [comment]
I think I got it working.

``` r
                                                                  
devtools::install_github("pmassicotte/eemR", ref = "read-generic")
#> Skipping install of 'eemR' from a github remote, the SHA1 (ae99a062) has not changed since last install.
#>   Use `force = TRUE` to force installation
                                                                  
library(eemR)                                                     
library(magrittr)                                                 
                                                                  
eems <- eem_read("~/Downloads/eem/") %>%                          
eem_remove_scattering("rayleigh") %>%                             
eem_remove_scattering("raman")                                    
                                                                  
plot(eems, 1)                                                     
```

![](http://i.imgur.com/bMXx5NO.png)

``` r
plot(eems, 2)                                                     
```

![](http://i.imgur.com/iqxBrqn.png)

``` r
plot(eems, 3)                                                     
```

![](http://i.imgur.com/Aj1FIlv.png)

``` r
plot(eems, 4)                                                     
```

![](http://i.imgur.com/PfmqIsQ.png)
