### ISSUE TITLE
EEM File from Perkin Elmer

### ISSUE THREAD

**Issue by ajngtc2312** [PMassicotte/eemR#49]
I have EEM files from Perkim Elmer that may be useful. The original file is in csv but I had to convert it to xlsx in order to upload it here. Do hope to see this format supported by eemR soon. 

Thanks!
Albert

[FEED.xlsx](https://github.com/PMassicotte/eemR/files/2955014/FEED.xlsx)

**Comment by PMassicotte** [comment]
Thank you!

**Comment by PMassicotte** [comment]
You can now use the dev version and write your own custom import function.
