### ISSUE TITLE
location is not set correctly after using eem_remove_blank

### ISSUE THREAD

**Issue by MatthiasPucher** [PMassicotte/eemR#52]
After using eem_remove_blank, the location of the samples is set to ".".
And eem_raman_normalisation does not work properly then.
I used version 1.0.0, the current GitHub master.

I hope, you can follow the problem with the code below:

```
require(eemR)

file <- system.file("extdata/cary/scans_day_1", "sample1.csv", package = "eemR")
eem <- eem_read(file, import_function = "cary")

file <- system.file("extdata/cary/scans_day_1", "nano.csv", package = "eemR")
blank <- eem_read(file, import_function = "cary")

eems <- eem_bind(eem,blank)

eems2 <- eem_remove_blank(eems)

lapply(eems2,`[[`,"location")

eems3 <- eem_raman_normalisation(eems2)
```

**Comment by PMassicotte** [comment]
Thanks for reporting it. I will correct it.

**Comment by PMassicotte** [comment]
@MatthiasPucher Can you try it now,.

**Comment by PMassicotte** [comment]
Also, can you also update your library? When it is done I will sen dit to CRAN.

**Comment by MatthiasPucher** [comment]
Thank you for fixing it so quickly!
I just updated and tried it again, everything works fine.
And thank you also for that package and the effort you put into it!
