### ISSUE TITLE
other file formats - TECAN

### ISSUE THREAD

**Issue by AnnaSege** [PMassicotte/eemR#68]
Hello, it would be awesome if it was either
- possible to use other input file formats. I am using TECAN device (see enclosed .
OR
- if there were Cary Eclipse and/or Aqualog dummy files available so that I could transform my files to that format.
[EEM.xlsx](https://github.com/PMassicotte/eemR/files/5605961/EEM.xlsx)

I don't mean file format in the form of csv or dat, but the actual organization of data inside those files.
I am already reorganizing my TECAN files so that they are compatible with the EEM package. I just need to know what willl work.

Best
Anna

**Comment by PMassicotte** [comment]
You can create your own import function. See here:

http://pmassicotte.github.io/eemR/articles/custom-import-function.html

**Comment by AnnaSege** [comment]
great, thanks!!
