### ISSUE TITLE
Error importing EEM folders using eem_read

### ISSUE THREAD

**Issue by brycook** [PMassicotte/eemR#70]
Hello I am having issues importing folders of EEM .dat files.

In the past I have used the following

`folder <- choose.dir()`
`eem_list <- eem_read(folder, import_function = "aqualog")`

to import an eem_list with no issues. But now, after updating R, I get the error "Error in file.info(file) : invalid filename argument". I reverted back to a previous version of R but the error persists.

I have noticed that eem_read allows me to import individual EEMs if I specify `file = "file path"` , however, I seemingly can no longer import entire folders with multiple eem files.

Please let me know if you have any questions or suggestions.

Thanks in advance!
-Bryce

**Comment by PMassicotte** [comment]
Can you send a folder  (zip file) with a couple of files in it?

**Comment by brycook** [comment]
[EEMs.zip](https://github.com/PMassicotte/eemR/files/8126736/EEMs.zip)

Here are some raw EEMs I processed last month successfully. Now I cannot read them using eemR.

-Bryce

**Comment by PMassicotte** [comment]
This works fine on my side.

``` r
library(eemR)

eems <- eem_read("~/Downloads/EEMs/", import_function = "aqualog")

plot(eems, 4)
```

![](https://i.imgur.com/JloCwOx.png)

<sup>Created on 2022-02-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Are you sure you have the latest version?

**Comment by brycook** [comment]
I am running eemR version 1.0.1 on R version 4.1.2 and I am still encountering this peculiar error.

**Comment by PMassicotte** [comment]
Maybe try to install the dev version and see if it works.

**Comment by brycook** [comment]
I tried devtools to no avail. Interestingly the code is working fine on all other lab computers except this one.

**Comment by brycook** [comment]
I have resolved the issue. Apparently with recent updates, I now have to be running RStudio and R using an admin account. Simple as that. Thanks again for your help.

**Comment by brycook** [comment]
Ok, so for some reason the code runs just fine in R GUI, but i encounter the issues when running in RStudio, and I'm not sure why.

**Comment by PMassicotte** [comment]
Hard to tell since I can not reproduce the problem. Feel free to reopen it if you find the reason.
